baseURL = 'https://cdndictionary.org/'
languageCode = 'en-us'
title = 'CDN Dictionary'
theme = "PaperMod"
paginate = 20
enableRobotsTXT = true
enableEmoji = true
mainSections = ["terms"]

[taxonomies]
    term = 'terms'
    tag = 'tags'

[minify]
    disableXML = true
    # minifyOutput = true

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 5

[[menu.main]]
identifier = "terms"
name = "terms"
url = "/terms/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "CDN Alliance"
name = "cdnlliance.org"
url = "https://cdnalliance.org"
weight = 30

[outputs]
    home = ['html', 'rss', 'json']

[Params]
env = "production"
title = "CDN Dictionary"
description = "The CDN Dictionary is a joint effort WorkingGroup by the CDN Alliance together with Tinify, Benocs and jsDelivr"
author = "CDN Alliance"
keywords = ["CDN", "Dictionary", "Content Delivery Network", "Glossary", "Terms", "Handbook"]
showtoc = true
ShowBreadCrumbs = true
defaultTheme = "auto"

  [Params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

[Params.homeInfoParams]
Title = "CDN Dictionary"
Content = """

Welcome to the CDN Dictionary by the [CDN Alliance](https://cdnalliance.org/), supported by [Tinify](https://tinify.com), [Benocs](https://benocs.com), and [jsDelivr](https://jsdelivr.com). 

This is your go-to resource for clear CDN terms and definitions. We've created it to help everyone, from newbies to experts, understand CDN jargon easily.


Join us in expanding this resource by collaborating on our [GitHub](https://github.com/cdn-Alliance/wg-dictionary/).
"""
    [[Params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/cdnallianceorg/"

    [[Params.socialIcons]]
    name = "Github"
    url = "https://github.com/cdn-Alliance/wg-dictionary/"


    [Params.editPost]
    URL = "https://github.com/CDN-Alliance/wg-dictionary/content"
    text = "Suggest Changes"
    appendFilePath = true
    disabled = false

[fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10
    keys = [ "title", "permalink", "summary", "content" ]
